print ("Hello World!")
print ("Hello Again...")
print ("I like typing this sentence.")
print ("This is fun.")
print ('Yay! its printing.')
print ("I'd like to add single quote.")
print ('I have added double-quote."')
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.')